version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - 9000:9000

  db:
    image: training_db:latest
    container_name: training-db
    restart: always
    build: ./db
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  clients:
    image: ghcr.io/mludeiro/training-go-clients:latest
    container_name: clients
    environment:
      MYSQL_DATABASE: 'TRAINING_CLIENTS'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '5000:5000'
    expose:
      - '5000'

  invoices:
    image: ghcr.io/mludeiro/training-go-invoices:latest
    container_name: invoices
    environment:
      MYSQL_DATABASE: 'TRAINING_INVOICES'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '5002:5002'
    expose:
      - '5002'

  products:
    image: ghcr.io/mludeiro/training-go-products:latest
    container_name: products
    environment:
      MYSQL_DATABASE: 'TRAINING_PRODUCTS'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '5001:5001'
    expose:
      - '5001'

volumes:
  my-db:
  portainer_data:
